<?php

/**
 * @file
 * Contains replicado.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function replicado_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the replicado module.
    case 'help.page.replicado':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Replicado Drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function replicado_theme($existing, $type, $theme, $path) {
  return array(
    'replicado' => array(
      'template' => 'replicado',
      'variables' => [
        'content' => NULL, 
        'label' => NULL, 
        'description' => NULL
      ],
    ),
      'docente' => array(
      'template' => 'docente',
      'variables' => [
        'content' => NULL, 
        'label' => NULL, 
        'description' => NULL
      ],
    ),
  );
}

